apiVersion: argoproj.io.v1alpha1
kind: Application
metadata: 
  name: dapps-election
  name: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/cyyeong/k8s-dapps-election-resources.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: ns-dapps-election

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true